# Deploy to digitalocean

name: Build and deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Image
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          ARGS: "-chavzP --stats"
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
          REMOTE_USER: ${{ secrets.DEPLOY_USERNAME }}
          REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
          TARGET: "${{ secrets.DEPLOY_TARGET }}"
      - name: Build image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            docker-compose -f production.yml down
            docker-compose -f production.yml up -d --build